library(reshape2)
library(ggplot2)
library(ape)
library(ggtree)
library(rgl)
library(vegan)

### Creating similarity distance triangle heat map
Betapartiti <- read.table("Betapartitivirus3_0506.txt", fill=TRUE, col.names=paste("V",1:35), row.names=1)
colnames(Betapartiti) <- rownames(Betapartiti)
Betapartiti <- apply(Betapartiti,2, function(x){(1/(1+x))*100})
Betapartiti <- melt(Betapartiti, na.rm=TRUE)

pdf("Betapartiti.pdf")
ggplot(data = Betapartiti, aes(Var1, Var2, fill = value))+
geom_tile(color = "white")+
scale_fill_gradient2(low = "blue", high = "red", mid = "yellow",
midpoint = 70, limit = c(40,100), space = "Lab",
name="Percentage\nSimilarity") +
geom_text(aes(label = round(value, 0)), size=1)+
theme_minimal()+
theme(panel.grid.major.x = element_line(size=.1, color="white") , panel.grid.major.y = element_line(size=.1, color="white"))+
theme(axis.text.x = element_text(angle = 90, vjust = 1,
size = 6, hjust = 1))+
theme(axis.text.y = element_text(angle = 0, vjust = 1,
size = 6, hjust = 1))+
coord_fixed()+
labs(x="Virus Names", y="Virus Names")
dev.off()

### Creating phylogenetic tree of fungal OTUs
info <- read.table("info.txt", header=TRUE, row.names=1)
tree<-read.tree("otu.tree")
p <- ggtree(tree, layout='circular') %<+% info +
geom_tippoint(aes(color=Division), size=1)+
scale_color_manual(values=c("green", "purple","red"))+
geom_tiplab(aes(color=Division, angle=angle), align=T, linetype="dotted", size=2, hjust=1, linesize = 0.2, offset=0.75)+
theme(legend.position = "top")

### creating animated 3D PCA plot with PCA data extracted from DeSeq2
pcaData <- read.table("pcaData.txt", sep="\t", header=TRUE, row.names=1)
colvec <- c("#FF0000", "#FF0000", "#FF0000", "#0000FF", "#0000FF", "#0000FF", "#000000", "#000000", "#808080", "#006600", "#006600", "#006600", "#FF8000", "#FF8000", "#FF8000", "#FF99FF", "#FF99FF", "#FF99FF", "#33FFFF", "#33FFFF", "#33FFFF", "#808080", "#000000", "#808080", "#66FF66", "#66FF66","#66FF66", "#FFFF00", "#FFFF00","#FFFF00")
legendCol <- c("#FF0000", "#0000FF","#000000","#006600","#FF8000","#FF99FF","#33FFFF","#808080","#66FF66","#FFFF00")
groups <- factor(pcaData$Gen)
levs <- levels(groups)
x=pcaData$PC1
y=pcaData$PC2
z=pcaData$PC3
groupCol <- c("#FF99FF","#33FFFF","#808080","#66FF66","#FFFF66")
# percentage variations for first 3 PCs have been taken from the Deseq data as 23, 16 and 15
percentVar <- c(23, 16, 15)
plot3d(pcaData[,1:3], col=colvec, size=2, type="s", lit=FALSE, xlim = c(-80,80), ylim=c(-50,50), zlim=c(-50,50), xlab=paste("PC1: 23% variance"), ylab=paste("PC2: 16% variance"), zlab=paste("PC3: 15% variance"))
#
for (i in 1:length(levs)) {
    group <- levs[i]
    selected <- groups == group
    xx <- x[selected]; yy <- y[selected]; zz <- z[selected]
    ellips <- ellipse3d(cov(cbind(xx,yy,zz)),
              centre=c(mean(xx), mean(yy), mean(zz)), level = 0.95)
    shade3d(ellips, col = groupCol[i], alpha = 0.1, lit = FALSE)}
# rsize manually to the rigth size and then create legend
legend3d("right", legend =legend, pch=16, col=legendCol, cex=2, inset=c(0.15))
dir.create("animation_merge")

for (i in 1:720) {
  view3d(userMatrix=rotationMatrix(2*pi * i/360, 0, 1, 0))
  rgl.snapshot(filename=paste("animation_merge/frame-",
                              sprintf("%03d", i), ".png", sep=""))}
# 
/SoftWare/Fiji.app/ImageJ-linux64
File > Import > Image Sequence
Image > type > 8-bit color
File >Save as > Animated gif

### Creating an ordination plot with vegan package and rda function
meta <- read.delim("meta.txt")
count_table <- read.delim("count_table.txt")
m1 <- rda(counts_kallisto ~ Gen, data=meta, scale=TRUE)
colvec <- c("black", "green4", "orange", "red2", "mediumblue")
colbg <- c("red2", "red2", "red2", "mediumblue", "mediumblue", "mediumblue", "black", "black", "white", "green4", "green4", "green4", "orange","orange","orange", "white", "white","white", "white","white", "white","white", "black", "white", "white","white", "white","white", "white","white")
leg.lvl <- c("R1", "R2", "R3", "S1", "S2", "untrt", "trt")
leg.col <- c("black", "green4", "orange", "red2", "mediumblue", "black", "black")
leg.bg <- c("black", "green4", "orange", "red2", "mediumblue", "white", "black")
PercentVar <- round(100 * summary(eigenvals(m1))[2,1:4])

plot(m1, choices=c(1,2), type = "n", xlim=c(-20,20), ylim=c(-20,20), xlab="", ylab="")
with(meta, points(m1, display = "sites", col = colvec[Gen], pch = 21, bg = colbg))
with(meta, ordiellipse(m1, Gen, kind="se", conf=0.95, col=colvec))
with(meta, ordispider(m1, Gen, col=colvec, label=FALSE))
with(meta, ordihull(m1, Gen, col=colvec, lty=2))
title(xlab=paste0("RD1: ",PercentVar[1],"% variance"), ylab=paste0("RD2: ",PercentVar[2],"% variance"), cex.lab=1.5, line=2.2)

plot(m1, choices=c(1,3), type = "n", xlim=c(-20,20), ylim=c(-20,20), xlab="", ylab="")
with(meta, points(m1, choices=c(1,3), display = "sites", col = colvec[Gen], pch = 21, bg = colbg))
with(meta, ordiellipse(m1, choices=c(1,3), Gen, kind="se", conf=0.95, col=colvec))
with(meta, ordispider(m1, choices=c(1,3), Gen, col=colvec, label=FALSE))
with(meta, ordihull(m1, choices=c(1,3), Gen, col=colvec, lty=2))
title(xlab=paste0("RD1: ",PercentVar[1],"% variance"), ylab=paste0("RD3: ",PercentVar[3],"% variance"), cex.lab=1.5, line=2.2)

###



